version: '3.7'
services:
  app:
    container_name: portfolio_diana_regina
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=development